### ISSUE TITLE
Add mail queue

### ISSUE THREAD

**Issue by linusgke** [WaldorfConnect/portal#25]
Add mail queue to avoid user error and to resend mail on failure

**Comment by linusgke** [comment]
check if delay between mail sending would be appropriate

**Comment by lchristmann** [comment]
### I measured how long the mail sending takes

![TimeLoggingAdded](https://github.com/WaldorfConnect/portal/assets/78609837/8df8ff33-8ad7-4f66-8552-19c4f7b83eeb)

### Results: (1 mail ~200ms ~0.2s | 5 mails per second)

```txt
25.11.2023 23:55:01
Working mail queue ...
Successfully sent mail 557 to lc-dev@proton.me
Mail sending took 170.50099372864 milliseconds.
```

```txt
25.11.2023 23:56:01
Working mail queue ...
Successfully sent mail 558 to lc-dev@proton.me
Mail sending took 202.56495475769 milliseconds.
Successfully sent mail 559 to linus@elektronisch.dev
Mail sending took 179.03399467468 milliseconds.
Successfully sent mail 560 to info.nsy@mailbox.org
Mail sending took 186.63620948792 milliseconds.
Successfully sent mail 561 to keivan.azimi.x@gmail.com
Mail sending took 356.23502731323 milliseconds.
Successfully sent mail 562 to Lara.sylla@mailbox.org
Mail sending took 174.98707771301 milliseconds.
Successfully sent mail 563 to fedo.kranz.smv@gmail.com
Mail sending took 180.42778968811 milliseconds.
Successfully sent mail 564 to nc.campregher06@outlook.de
Mail sending took 245.89610099792 milliseconds.
Successfully sent mail 565 to Hannah.Rabea.Eilert@gmail.com
Mail sending took 287.91904449463 milliseconds.
Successfully sent mail 566 to leanderbesand007@icloud.com
Mail sending took 174.86310005188 milliseconds.
Successfully sent mail 567 to leneriksson@web.de
Mail sending took 150.13718605042 milliseconds.
Successfully sent mail 568 to jojoembe@gmail.com
Mail sending took 167.04893112183 milliseconds.
Successfully sent mail 569 to simon@ruprechts.com
Mail sending took 186.60807609558 milliseconds.
Successfully sent mail 570 to alpinxtime@gmx.de
Mail sending took 156.8329334259 milliseconds.
Successfully sent mail 571 to d.lindenthal@mnet-mail.de
Mail sending took 156.57091140747 milliseconds.
Successfully sent mail 572 to anne.bartel2005@gmail.com
Mail sending took 176.2170791626 milliseconds.
Successfully sent mail 573 to leander.christmann@proton.me
Mail sending took 144.85001564026 milliseconds.
Successfully sent mail 574 to lc-dev@proton.me
Mail sending took 143.80288124084 milliseconds.
```

**Comment by lchristmann** [comment]
This means in the above case for example (new user accepted, sending 20 mails to all global admins), the system would be burdened for 2 seconds.

The Apache will still be able to handle user requests in that time, [since it handles multiple requests in parallel](https://stackoverflow.com/questions/21340076/how-does-php-and-apache-handle-multiple-requests). How big will the load be, is it noticeable? Idk...

But having the mail-sending thread [sleep](https://www.php.net/manual/en/function.usleep.php) for a bit, could definitely distribute the load, so it becomes even less noticeable.

We'd just have to care that (1) the mails may never pile up and (2) we don't delay too much, because people rather don't want to wait more than a minute for their mail to come.

-> So just a little delay. Maybe just 100 milliseconds?
This way there could still be 100 mails sent in 30 seconds (200/s).
We should definitely keep mailling power up, since mails stack up fast when operations happen that notify all global admins.

### I'm in for `100ms` or at most `200ms` delay.

**And when we want to optimize on that, we get a separate mail server and use its asynchronous API. That's would be the best solution anyway.**

**Comment by linusgke** [comment]
Awesome research! I'd also say that that 100ms would be appropriate.

**Comment by lchristmann** [comment]
Before implementing this, I want to see how much changes when reusing the $mailer object:

![TimeLoggingReusingMailerObject](https://github.com/WaldorfConnect/portal/assets/78609837/d773b4af-5be9-41aa-bb20-35790d1a252c)

### Results (1 mail ~160ms ~0.16s | 6.25 mails per second)<br>Performance gains: 25% | 1 mail ~40ms less | 1.25 more mails per second | 75 more mails per minute

```txt
26.11.2023 13:04:01
Working mail queue ...
Successfully sent mail 612 to lc-dev@proton.me
Mail sending took 151.09205245972.
```

```txt
26.11.2023 13:08:02
Working mail queue ...
Successfully sent mail 613 to lc-dev@proton.me
Mail sending took 154.45017814636.
```

```txt
26.11.2023 13:09:01
Working mail queue ...
Successfully sent mail 614 to lc-dev@proton.me
Mail sending took 151.41701698303.
Successfully sent mail 615 to linus@elektronisch.dev
Mail sending took 168.61796379089.
Successfully sent mail 616 to info.nsy@mailbox.org
Mail sending took 161.03982925415.
Successfully sent mail 617 to m.h.gr@icloud.com
Mail sending took 179.00991439819.
Successfully sent mail 618 to keivan.azimi.x@gmail.com
Mail sending took 161.95893287659.
Successfully sent mail 619 to Lara.sylla@mailbox.org
Mail sending took 144.6270942688.
Successfully sent mail 620 to fedo.kranz.smv@gmail.com
Mail sending took 176.40089988708.
Successfully sent mail 621 to nc.campregher06@outlook.de
Mail sending took 192.97194480896.
Successfully sent mail 622 to Hannah.Rabea.Eilert@gmail.com
Mail sending took 162.09602355957.
Successfully sent mail 623 to leanderbesand007@icloud.com
Mail sending took 189.30912017822.
Successfully sent mail 624 to leneriksson@web.de
Mail sending took 147.91917800903.
Successfully sent mail 625 to jojoembe@gmail.com
Mail sending took 176.90801620483.
Successfully sent mail 626 to simon@ruprechts.com
Mail sending took 171.83804512024.
Successfully sent mail 627 to alpinxtime@gmx.de
Mail sending took 145.3230381012.
Successfully sent mail 628 to d.lindenthal@mnet-mail.de
Mail sending took 157.57989883423.
Successfully sent mail 629 to anne.bartel2005@gmail.com
Mail sending took 151.02505683899.
Successfully sent mail 630 to leander.christmann@proton.me
Mail sending took 197.82996177673.
Successfully sent mail 631 to schuberth.julius@gmail.com
Mail sending took 153.04780006409.
```

**Comment by lchristmann** [comment]
Based on above discussion and measurements, I will implement:

- a `100ms` sleep with [usleep()](https://www.php.net/manual/en/function.usleep.php) after sending a mail. [This should use the OS' `sleep` making the thread take almost no CPU time and letting other threads have it](https://en.wikipedia.org/wiki/Busy_waiting#Alternatives).
- the re-usage of the `$mailer` object. [Throughout the `sleep` period this object will stay in memory and not get stolen and killed by the garbage collector](https://stackoverflow.com/a/5372387/20594090) - so there should be no problem.

**Comment by lchristmann** [comment]
✅ [Implemented in this commit.](https://github.com/WaldorfConnect/portal/commit/689091c624e53ac4d2fa75d931b2e95f96a69294)
