### ISSUE TITLE
Add `website_url` to school and group

### ISSUE THREAD

**Issue by linusgke** [WaldorfConnect/portal#32]

**Comment by linusgke** [comment]
Already added columns to database

**Comment by lchristmann** [comment]
**added website_urls for 3 schools and groups each** in database: (to verify implementation)

**schools:** FWS Augsburg, FWS Chiemgau, FWS Erlangen
**groups:** WaldorfConnect, WaldorfSV, W-LSV Bayern

**Comment by lchristmann** [comment]
done, for both schools and groups

- added `website` property in Group/School **Model** and **Entity**
- added `website` property in Group/School**View**
- add `website` property in **Admin Create** (incl. **Helper**) and **Edit Views**
- added `website` property in **AdminController**

(and added missing image_author to school and group Model `$allowedFields`)

**Comment by lchristmann** [comment]
✅ deployed and fully tested it
(created, edited and viewed everything, schools & groups)
