### ISSUE TITLE
Add resend email confirmation

### ISSUE THREAD

**Issue by linusgke** [WaldorfConnect/portal#33]
- Add button to resend email confirmation message to ProfileView

- Add option to resend email after registration

**Comment by linusgke** [comment]
I wanted to add a button to ProfileView to trigger a resend of the email confirmation mail.

In case someone accidentally deleted the email from his inbox.

**Comment by linusgke** [comment]
Same with registration. After a user registered he should have the option to trigger an email resend by clicking a button on the RegisterView.

For all of this, we should move the email confirmation logic to its own helper method.

**Comment by lchristmann** [comment]
Ahhh with the **first point** you mean adding said button to the `EditProfileView.php` for **email confirmation after someone changed his email by himself**.

And the **second point** relates to the **email confirmation requried after registration**.
