### ISSUE TITLE
Lazy load school and group images

### ISSUE THREAD

**Issue by linusgke** [WaldorfConnect/portal#34]
- [x] [Implement java-script lazy loading for images](https://www.w3schools.com/tags/att_img_loading.asp)
- [x] No longer use deprecated `onerror` attribute
- [x] No longer use `placehold.co` placeholders

**Comment by lchristmann** [comment]
Suggestion:

- solve point 2 and 3 by simply deleting the `onerror` attributes (they have the https://`placehold.co`/... placeholders as values)

Reason:

- fallbacks for images are not commonly required (it's rather unusual)

**Comment by lchristmann** [comment]
Implementation:
- download all the used placeholders into the assets folder
- implement the if else statement

Extra:
- set encoding to UTF-8 for the app (php.ini file) and for the MySQL database

> Encoding of LDAP [is always UTF-8 by default since ldap3](https://ldap3.readthedocs.io/en/latest/encoding.html)

Push & Deployment:
- push the code & deploy it to the server
