### ISSUE TITLE
Add image upload to school and group edit

### ISSUE THREAD

**Issue by linusgke** [WaldorfConnect/portal#35]
[CodeIgniter 4 Documentation: Working with Uploaded Files](https://codeigniter.com/user_guide/libraries/uploaded_files.html)

**Comment by lchristmann** [comment]
@linusgke How about adding image upload to school/group create view?
We could
1. first save the text data to the database
2. take the `$id` (from the database) that the `saveSchool`/`saveGroup` function returns
3. and with that store the image file under the right path

**Comment by linusgke** [comment]
Would be great!! It should be optional though.

**Comment by lchristmann** [comment]
@linusgke Image upload refers to both image types, right?
- logo.png
- image.png

**Comment by lchristmann** [comment]
In this issue the limitation of only having `.png` files ist kept.
Support for various image formats will be implemented in [#39 "Support various image formats for schools and groups"](https://github.com/WaldorfConnect/portal/issues/39)
