### ISSUE TITLE
Support various image formats for schools and groups

### ISSUE THREAD

**Issue by lchristmann** [WaldorfConnect/portal#39]
Currently only PNG images can be uploaded - although there are other very common ones:

- JPG / JPEG
- GIF
- WEBP

Those should be supported as well, in order not to cause the users any trouble.

Approach & Resources:

1. [This StackOverflow answer shows an example of allowing only specific image formats on the frontend.](https://stackoverflow.com/a/6225815/20594090)
2. [The docs of CodeIgniter show how to validate those formats on the backend.](https://codeigniter.com/user_guide/libraries/uploaded_files.html#the-controller)
3. In the Group and School View, when loading those images, we have to look for a file `/assets/img/group/2/logo.*` (with wildcard character). Then frontend and backend validation ensures that that will be a valid image file.

**Comment by linusgke** [comment]
We could also look into 'imagewebp' module and convert all uploaded images to .webp in order to ensure small files and less traffic.

https://stackoverflow.com/questions/26314508/convert-jpg-to-webp-using-imagewebp

**Comment by lchristmann** [comment]
> We could also look into 'imagewebp' module and convert all uploaded images to .webp in order to ensure small files and less traffic.
> 
> https://stackoverflow.com/questions/26314508/convert-jpg-to-webp-using-imagewebp

That would be the cleanest solution, I agree. Let's try that first (inside a new helper `Helpers\image_helper.php`).

**Comment by linusgke** [comment]
Yeah, perfect.
