### ISSUE TITLE
Reflecting on the permission system

### ISSUE THREAD

**Issue by linusgke** [WaldorfConnect/portal#46]
Currently a REGION_ADMIN may only manage the region his school is in. Consequences of this are, that one person may only manage one region.

In an effort to reduce the number of global admins, it might become useful to be able to grant REGION_ADMINs access to multiple regions.

I'm thinking of redoing the permission system, by completely going away from the "_ADMIN" role, more to access granted on individual entities (schools, groups)

**Comment by lchristmann** [comment]
I think our current system of having `schools`, `regions` and `global` is good, because it reflects the organizational levels: `SMVs`, `W-LSVs` and the `W-SV/WaldorfConnect team`.

However we should indeed modify it to be more granular.

> Somebody like a `Keivan Azimi` should probably be admin of his home town school and of the `Bayern` region, which he looks after. Some people might administer multiple schools. Some might need multiple regions.

I'm thinking of a `portal_admins`  table, that maps `users` and `schools/groups` `N:M` (many to many). The GLOBAL_ADMIN role can then be an on-off flag (a boolean) in the `portal_users` table.

**Comment by lchristmann** [comment]
Rework of our permission system:

- we don't differentiate between `groups` and `schools` anymore: it's just `groups`
- there are `GLOBAL-ADMINS`, `REGOIN-ADMINS` and `GROUP-ADMINS`
- `groups` can be subordinated to `regions`, but **they don't have to be**
  - if a `group` has a `region`, its `group admins` + the `region admins` + `global admins` can manage it
  - if a `group` has **no** `region`, its `group admins` + `global admins` can manage it

![Berechtigungsstruktur](https://github.com/WaldorfConnect/portal/assets/78609837/3218da58-8c98-488b-9eae-0db8315f5f08)

Reasoning for allowing groups without a region:

- there are projects or groups that don't see themselves as subordinated to any regional council/administrators, like a temporary group organizing a conference

Technical implementation proposal for groups without a region:

- we allow the `region_id` of the database to be NULL for `groups` that don't have a region

**Comment by linusgke** [comment]
Agree! Changing implementation to expect that the region id might be null.

**Comment by linusgke** [comment]
Overhaul of permission system was finished with https://github.com/WaldorfConnect/portal/commit/a6868da074bd090b3ab88909f36bdf0014fdcd09

There is now only a user-bound boolean value specifying global admin privileges. Regionalized are no longer a matter of programmatic implementation but organizational structures (e.g., having global admins in each region)
